repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true
        args: [--config, dev_configurations/.flake8]
      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: system
        types_or: [cython, pyi, python]
        args: ["--filter-files"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        description: Automatically upgrade syntax for newer versions.
        args: [--py310-plus]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        description: Prevent giant files from being committed.
        args: ["--maxkb=500"]
      - id: check-ast
        description: Simply check whether files parse as valid python.
      - id: check-executables-have-shebangs
        description: Checks that non-binary executables have a proper shebang.
      - id: check-json
        description: Attempts to load all json files to verify syntax.
      - id: check-toml
        description: Attempts to load all TOML files to verify syntax.
      - id: check-yaml
        description: Attempts to load all yaml files to verify syntax.
      - id: end-of-file-fixer
        description: Makes sure files end in a newline and only a newline.
      - id: name-tests-test
        description: verifies that test files are named correctly.
        args: ["--pytest-test-first"]
      - id: trailing-whitespace
        description: Trims trailing whitespace.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
