version: "3.9"
services:
  ml:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        PYTHON_VERSION: "3.10"
      tags:
        - {{cookiecutter.project_name}}
    volumes:
      - ~/{{cookiecutter.project_name}}:/home/{{cookiecutter.project_name}}
    # This is to allow for a long running container so VSCode can attach to it
    command: tail -F anything
    privileged: true
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=video,compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]