version: "3.9"
networks:
  mongo-network:
    name: mongo-network
    external: true
services:
  ml:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        PYTHON_VERSION: "3.10"
      tags:
        - {{cookiecutter.project_name}}
    volumes:
      - ~/{{cookiecutter.project_name}}:/home/{{cookiecutter.project_name}}
    command: tail -F anything
    networks:
      - mongo-network
    privileged: true
    environment:
      - FIFTYONE_DATABASE_URI=mongodb://${MONGO_USER}:${MONGO_USER_PASSWORD}@${MONGO_IP}:27017/?authSource=admin
      - NVIDIA_DRIVER_CAPABILITIES=video,compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
            # Only says one but it actually can use all gpus
              count: 1
              capabilities: [gpu]