version: "3.9"
networks:
  ml-network:
    name: ml-network
    external: true
services:
  ml:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        PYTHON_VERSION: "3.10"
      tags:
        - {{cookiecutter.project_name}}
    ports:
      # exposes this port so if a fiftyone app is started, you can view the app in your browser at localhost:5151
      - 5151:5151
    shm_size: 64g
    volumes:
      - /fiftyone/data/media:/root/fiftyone
      - ~/{{cookiecutter.project_name}}:/home/{{cookiecutter.project_name}}
    command: tail -F anything
    networks:
      - ml-network
    privileged: true
    environment:
      - FIFTYONE_DATABASE_URI=mongodb://${MONGO_USER}:${MONGO_USER_PASSWORD}@${MONGO_IP}:27017/?authSource=admin
      - QDRANT_IP=${QDRANT_IP}
      - NVIDIA_DRIVER_CAPABILITIES=video,compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
            # Only says one but it actually can use all gpus
              count: 1
              capabilities: [gpu]