name: Linting and Type Checking
on: [push]
jobs:
  black:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3.3.0
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"
      - name: Install black
        run: pip install black
      - name: Check black
        run: black --verbose .

  flake8:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3.3.0
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"
      - name: Install flake8
        run: pip install flake8
      - name: Check flake8
        run: flake8 --config dev_configurations/.flake8 .

  isort:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3.3.0
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"
      - name: Install isort
        run: pip install isort
      - name: Check isort
        run: isort . --check --diff --verbose

  pyright:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3.3.0
      - name: Install poetry
        run: pip install poetry
      - name: Check poetry version
        run: poetry --version
      - name: Cache Python Dependencies
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"
          cache: poetry
      - name: Install python packages for type checking
        run: poetry install
      - name: Check pyright
        run: poetry run pyright